---
title: "Rotate Schaefer 200x17"
output: html_document
---

Produces spherical rotations of schaefer 200x17 for spin testing
```{r setup, include=FALSE}
library(freesurfer)
library(freesurferformats)
# rotate.parcellation.R and perm.sphere.p.R are downloaded from https://github.com/frantisekvasa/rotate_parcellation
source("/cbica/projects/network_replication/software/rotate.parcellation.R")
source("/cbica/projects/network_replication/software/perm.sphere.p.R")

```

```{r}
# Extract parcel centroid coordinates on the fsaverage sphere from Schaefer .annot files
# load freesurfer fsaverage surface
lh <- read.fs.surface("/cbica/projects/network_replication/software/rotate_parcellation/lh.sphere") # downloaded from freesurfer/subjects/fsaverage/surf
rh <- read.fs.surface("/cbica/projects/network_replication/software/rotate_parcellation/rh.sphere")

extract_centroid_coords <- function(schaefer_atlas, network_parcellation) {
  lh.schaefer.annot <- read_annotation(sprintf("/cbica/projects/network_replication/software/rotate_parcellation/annot/lh.Schaefer2018_%1$sParcels_%2$sNetworks_order.annot", schaefer_atlas, network_parcellation))
  rm <- which(lh.schaefer.annot$colortable$label=="Background+FreeSurfer_Defined_Medial_Wall")
  lhcoords <- t(sapply(c(1:length(lh.schaefer.annot$colortable$label))[-rm], function(x) colMeans(lh$vertices[which(lh.schaefer.annot$label==lh.schaefer.annot$colortable$code[x]),]) ))
  
  rh.schaefer.annot <- read_annotation(sprintf("/cbica/projects/network_replication/software/rotate_parcellation/annot/rh.Schaefer2018_%1$sParcels_%2$sNetworks_order.annot", schaefer_atlas, network_parcellation))
  rm <- which(rh.schaefer.annot$colortable$label=="Background+FreeSurfer_Defined_Medial_Wall")
  rhcoords <- t(sapply(c(1:length(rh.schaefer.annot$colortable$label))[-rm], function(x) colMeans(rh$vertices[which(rh.schaefer.annot$label==rh.schaefer.annot$colortable$code[x]),]) ))
  
  schaefer.fsaverage.coords <- rbind(lhcoords,rhcoords)
  write.csv(schaefer.fsaverage.coords, sprintf("/cbica/projects/network_replication/software/rotate_parcellation/schaefer%1$sx%2$s_sphericalcoords.csv", schaefer_atlas, network_parcellation), row.names=F)
    
} 
 
extract_centroid_coords(200, 17) # schaefer200x17

# label the coordinates of schaefer200x17.coords parcel centroids on the freesurfer sphere
schaefer200x17.coords <- read.csv("/cbica/projects/network_replication/software/rotate_parcellation/schaefer200x17_sphericalcoords.csv") 
lh.schaefer.annot <- read_annotation(sprintf("/cbica/projects/network_replication/software/rotate_parcellation/annot/lh.Schaefer2018_%1$sParcels_%2$sNetworks_order.annot", 200, 17))
rh.schaefer.annot <- read_annotation(sprintf("/cbica/projects/network_replication/software/rotate_parcellation/annot/rh.Schaefer2018_%1$sParcels_%2$sNetworks_order.annot", 200, 17))
label <- data.frame(c(lh.schaefer.annot$colortable[2:101,1], rh.schaefer.annot$colortable[2:101,1]))
schaefer200x17.coords <- cbind(label, schaefer200x17.coords)
names(schaefer200x17.coords)[1] <- "label" 
write.csv(schaefer200x17.coords, sprintf("/cbica/projects/network_replication/software/rotate_parcellation/schaefer%1$sx%2$s_sphericalcoords.csv", 200, 17), row.names=F) # saved out with labels now
 
set.seed(10)
perm.id.full <- rotate.parcellation(coord.l = as.matrix(schaefer200x17.coords[1:100,2:4]), coord.r = as.matrix(schaefer200x17.coords[101:200,2:4]), nrot = 10000) #rotate the schaefer200.coords parcellation 10,000 times on the freesurfer sphere to generate spatial nulls for spin-based permutation significance testing 
saveRDS(perm.id.full, "/cbica/projects/network_replication/software/rotate_parcellation/schaefer200x17.coords_sphericalrotations_N10k_seed10.rds")
 
```

